### ISSUE TITLE
Stadt- und Regionalbibliothek Erfurt

### ISSUE THREAD

**Issue by impeira** [stefanw/voebbot#24]
**URL des Digitalangebots der Bibliothek**
https://erfurt.de/bibliothek

**Hat die Bibliothek Genios, Munzinger, NexisUni oder andere Pressedatenbanken im Angebot?**
https://bib-erfurt.genios.de/
https://www.munzinger.de/search/login?portalid=57251

**Comment by PascalKoe** [comment]
I have added Erfurt to my fork. Could you try if it works so I can create a pull request?

If you are on a Linux computer or have WSL enabled and NodeJS installed, you can simply run the ``dist.sh`` file to build the extension. If you don't want to build it yourself, you can download a release from [https://github.com/PascalKoe/voebbot/releases/tag/v0.12.1](https://github.com/PascalKoe/voebbot/releases/tag/v0.12.1).

To install the extension you need to use the developer mode because the extension you build yourself/was build by me isn't signed. To do so in Firefox, open a new tab and type in ``about:debugging``. There you need to select ``This Firefox`` on the left hand side. In the main area there should now be a button ``Load Temporary Add-on…``. If this button is not visible, you need to click on the heading ``Temporary Extensions`` and the button should become visible. After clicking the button a window to select a file should open.  Select the release zip file you downloaded or build yourself in the ``dist`` directory. The extension should now be loaded and ready to be tested.

**Comment by impeira** [comment]
I tried it already myself (added Erfurt to v0.12.0) and it worked perfectly.

**Comment by impeira** [comment]
That also applies to V0.12.1. 👍
